server:
  port : 8099

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/mutant_operation
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
